---
- name: Ensure tmp directory exists
  ansible.builtin.file:
    path: "{{ tmp_dir }}"
    state: directory
    mode: "0777"

- name: Clone the repository to /tmp
  ansible.builtin.git:
    repo: "{{ vars[project][type][client].source_url }}"
    dest: "{{ tmp_dir }}/{{ service_identifier }}"
    version: "{{ vars[project][type][client].version }}"
    force: true

- name: Build the project using `go build`
  ansible.builtin.command: go build -o story ./client
  args:
    chdir: "{{ tmp_dir }}/{{ service_identifier }}"
  environment:
    PATH: "{{ go.root }}/bin:{{ ansible_env.PATH }}"
    GOROOT: "{{ go.root }}"
    GOPATH: "{{ go.path }}"
    GO111MODULE: "{{ go.module111 }}"
  changed_when: false

- name: Find the built binary
  ansible.builtin.find:
    paths: "{{ tmp_dir }}/{{ service_identifier }}"
    patterns: "{{ consensus_default_binary_name }}"
    recurse: true
  register: binary_location

- name: Copy the built binary to the target directory
  ansible.builtin.copy:
    src: "{{ binary_location.files[0].path }}"
    dest: "{{ consensus_bin_dir }}/{{ service_identifier }}"
    mode: "0755"
    owner: root
    group: root
    remote_src: true

- name: Clean up the temporary repository directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: absent
