---
- name: Set project and service identifier in facts
  ansible.builtin.set_fact:
    project: "{{ group_names[0] }}"
    service_identifier: >-
      {{ group_names[0] }}{{ '-' + client if type in default_node_types and client is defined else '-' + type + ('-' + client if client is defined else '') }}

- name: Set architecture variable based on system architecture
  ansible.builtin.set_fact:
    system_architecture: >-
      {%- if ansible_architecture == 'x86_64' -%}
        amd64
      {%- elif ansible_architecture == 'aarch64' -%}
        arm64
      {%- else -%}
        {{ ansible_architecture }}
      {%- endif -%}

- name: Display environment being deployed to
  ansible.builtin.debug:
    msg:
      - "Deploying to Host: {{ inventory_hostname }}"
      - "Groups: {{ group_names }}"
      - "Project: {{ project }}"
      - "Environment: {{ env }}"
      - "Type: {{ type }}"
      - "Version: {{ vars[project][type]['execution' if client == 'execution' else 'consensus'].version }}"
      - "Username: {{ service_identifier }}"
      - "Service Name: {{ service_identifier }}"
      - "Operating System: {{ ansible_system | lower }}"
      - "System Architecture: {{ system_architecture }}"

- name: Set all port variables dynamically
  ansible.builtin.set_fact:
    p2p_port: "{{ vars[project][type][client].ports.prefix ~ vars[project][type][client].ports.suffix.p2p }}"
    rpc_port: "{{ vars[project][type][client].ports.prefix ~ vars[project][type][client].ports.suffix.rpc }}"
    abci_port: "{{ vars[project][type][client].ports.prefix ~ vars[project][type][client].ports.suffix.abci }}"
    prometheus_port: "{{ vars[project][type][client].ports.prefix ~ vars[project][type][client].ports.suffix.prometheus }}"
    pprof_port: "{{ vars[project][type][client].ports.prefix ~ vars[project][type][client].ports.suffix.pprof }}"
    rest_api_port: "{{ vars[project][type][client].ports.prefix ~ vars[project][type][client].ports.suffix.rest_api }}"
    rosetta_port: "{{ vars[project][type][client].ports.prefix ~ vars[project][type][client].ports.suffix.rosetta }}"
    grpc_port: "{{ vars[project][type][client].ports.prefix ~ vars[project][type][client].ports.suffix.grpc }}"
    grpc_web_port: "{{ vars[project][type][client].ports.prefix ~ vars[project][type][client].ports.suffix.grpc_web }}"
  when: vars[project][type][client].ports.prefix is defined

- name: Display all port variables
  ansible.builtin.debug:
    msg:
      - "P2P Port: {{ p2p_port }}"
      - "RPC Port: {{ rpc_port }}"
      - "ABCI Port: {{ abci_port }}"
      - "Prometheus Port: {{ prometheus_port }}"
      - "Pprof Port: {{ pprof_port }}"
      - "REST API Port: {{ rest_api_port }}"
      - "Rosetta Port: {{ rosetta_port }}"
      - "gRPC Port: {{ grpc_port }}"
      - "gRPC-Web Port: {{ grpc_web_port }}"
  when: vars[project][type][client].ports.prefix is defined

- name: Confirm deployment details
  ansible.builtin.pause:
    prompt: Press 'Enter' to continue with the deployment or Ctrl+C to cancel

- name: Please confirm again
  ansible.builtin.debug:
    msg:
      - "Deploying to Host: {{ inventory_hostname }}"
      - "Project: {{ project }}"
      - "Environment: {{ env }}"
      - "Type: {{ type }}"

- name: Confirm deployment details
  ansible.builtin.pause:
    prompt: Press 'Enter' to continue with the deployment or Ctrl+C to cancel
