---
- name: Include user creation task for sui
  ansible.builtin.include_tasks: tasks/create_user_and_directories.yml
  vars:
    home: "{{ bridge_home_dir }}"
    directories: "{{ bridge_directories }}"
    log_file_path: "{{ bridge_log_file_path }}"

- name: Copy bridge configuration file
  ansible.builtin.template:
    src: "{{ env }}/bridge.yaml.j2"
    dest: "{{ bridge_config_file_path }}"
    owner: "{{ service_identifier }}"
    group: "{{ service_identifier }}"
    mode: "0644"
  notify:
    - Restart service

- name: Fetch secrets from HCP Vault and save to files
  block:
    - name: Fetch authority key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ bridge_authority_key_file_name }}"
        secret_destination_path: "{{ bridge_authority_key_path }}"
        secret_type: key

    - name: Fetch client key and save
      ansible.builtin.include_tasks: tasks/get_and_save_vault_secret.yml
      vars:
        vault_secret_source_path: "{{ project }}/{{ org }}/{{ type }}/{{ bridge_client_key_file_name }}"
        secret_destination_path: "{{ bridge_client_key_path }}"
        secret_type: key

- name: Fetch binaries
  block:
    - name: Fetch the service binary
      ansible.builtin.get_url:
        url: "{{ sui.bridge.source_url }}/{{ sui.bridge.version }}/{{ bridge_service_default_binary_name }}"
        dest: "{{ bridge_bin_dir }}/{{ service_identifier }}"
        owner: root
        group: root
        force: true
        mode: "0755"
      notify:
        - Restart service

    - name: Fetch the cli binary
      ansible.builtin.get_url:
        url: "{{ sui.bridge.source_url }}/{{ sui.bridge.version }}/{{ bridge_cli_default_binary_name }}"
        dest: "{{ bridge_bin_dir }}/{{ bridge_cli_default_binary_name }}"
        owner: root
        group: root
        force: true
        mode: "0755"

- name: Copy sui-node systemd service file
  ansible.builtin.template:
    src: "{{ env }}/sui-bridge.service.j2"
    dest: /etc/systemd/system/{{ service_identifier }}.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload service
    - Restart service
