---
# maintains file name, binary names, and anything which is not a diretcory or path

# config file names
bridge_config_file_name: config.yaml
bridge_authority_key_file_name: authority.key
bridge_client_key_file_name: client.key

# binary names
bridge_service_default_binary_name: sui-bridge
bridge_cli_default_binary_name: sui-bridge-cli
